### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by astratagem** [johnae/nix-flake-templates#1]
Hi @johnae, 

I'm really liking the templates you've provided, especially the well-documented template for devshell usage. 

I would like to use and adapt your work here for my own use cases, but there's no license info available. Could you please add a LICENSE.md file? Preferably a free software license like GPLv3, GPLv2, or MIT. 

Thanks!

**Comment by johnae** [comment]
Hey @montchr! Glad you like these. Tbh I haven't given licensing much thought as I believed I was the only user. Glad you brought it up. I'll just license these under the MIT License I think. Will do so later today if I have time.

**Comment by johnae** [comment]
@montchr Added MIT license.
